name: HVF_Power_On
on: [workflow_dispatch]

jobs:
  run-logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute Handshake
        run: python3 src/livestock/triad_link.py
